name: TikTok Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install

      - name: Run script
        run: python main.py
